export type Product = {
  id: number
  name: string
  description: string
  price: number
  priceStr: string
  size: string
  image: string
  category: 'Camarão Turbo' | 'Pirata Turbo' | 'Shad Turbo' | 'Shad Pirata' | 'Caixa / Kit'
}

export const products: Product[] = [
  // ── Camarão Turbo ──────────────────────────────────────────────────────────
  {
    id: 1,
    name: 'Camarão Turbo – Apache',
    description: 'Isca de silicone macio modelo Camarão Turbo na cor Apache. Movimento ultra-realista, ideal para robalo, pescada e tainha em mar e estuário.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-apache.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 2,
    name: 'Camarão Turbo – Coringa',
    description: 'Cor Coringa multicolor com alto poder de atração. Perfeita para dias de sol forte com água clara.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-coringa.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 3,
    name: 'Camarão Turbo – Descascado',
    description: 'Modelo Descascado, silicone translúcido que imita perfeitamente o camarão natural. Excelente para pescarias em águas claras.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-disincapdo.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 4,
    name: 'Camarão Turbo – Ferrinho Ovado',
    description: 'Variante Ferrinho com ovos embutidos no corpo, imitando fêmea prenha — irresistível para predadores seletivos.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-ferrinho-ovado.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 5,
    name: 'Camarão Turbo – Ferrinho',
    description: 'Cor Ferrinho metálica com reflexo que atrai predadores em qualquer nível de profundidade.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-ferrinho.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 6,
    name: 'Camarão Turbo – Fumaça Ova Black',
    description: 'Corpo Fumaça transparente com ovos pretos — combinação que engana até os predadores mais experientes.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-fumaca-ova-black.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 7,
    name: 'Camarão Turbo – Fumaça',
    description: 'Clássico Fumaça translúcido com glitter e placa holográfica central. Versátil para qualquer condição de pesca.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-fumaca.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 8,
    name: 'Camarão Turbo – Ouro Ovado',
    description: 'Cor Ouro com ova — combinação premium que se destaca em qualquer ambiente aquático.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-ouro-ovado.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 9,
    name: 'Camarão Turbo – Ova Red',
    description: 'Silicone com ova vermelha viva — simula camarão em período reprodutivo, aumentando muito o poder de atração.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-ova-red.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 10,
    name: 'Camarão Turbo – Ova Verde',
    description: 'Ova verde para ambientes com vegetação subaquática. Mimetismo perfeito para pesca em manguezais.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-ova-verde.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 11,
    name: 'Camarão Turbo – Palhacinho',
    description: 'Cor Palhacinho vibrante, multicolorida. Ótima para provocar ataque por curiosidade e territorialidade.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-palhacinho.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 12,
    name: 'Camarão Turbo – Prateado',
    description: 'Finish prateado altamente refletivo. Funciona excelente em dias nublados ou em águas escuras.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-prateado.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 13,
    name: 'Camarão Turbo – Rosa',
    description: 'A cor Rosa é a queridinha dos pescadores. Alta atração para robalo e corvina em qualquer fundo.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-rosa.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 14,
    name: 'Camarão Turbo – Roxinho',
    description: 'Cor Roxinho exclusiva Piratas, desenvolvida para pesca noturna e em águas turvas.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-roxinho.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 15,
    name: 'Camarão Turbo – Spartano',
    description: 'Cor Spartano bold para pescadores que buscam destaque. Indicado para pesca embarcada.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-spartano.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 16,
    name: 'Camarão Turbo – Tricolor Cauda Verde',
    description: 'Corpo tricolor com cauda verde fluorescente — combinação de alto contraste para dias de alta turbidez.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-tricolor-cauda-verde.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 17,
    name: 'Camarão Turbo – Tricolor',
    description: 'Tricolor clássico com três tons que imitam o camarão natural em diferentes fases de muda.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-tricolor.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 18,
    name: 'Camarão Turbo – Verde Pirata',
    description: 'Verde Pirata — cor exclusiva da marca, desenvolvida para manguezais e rios com fundo vegetal.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-verde-pirata.jpg',
    category: 'Camarão Turbo',
  },
  {
    id: 19,
    name: 'Camarão Turbo – Red Turbo',
    description: 'Red Turbo de alto impacto visual. Excelente para robalo em água limpa e com correnteza.',
    price: 9.9,
    priceStr: 'R$ 9,90',
    size: '9 cm',
    image: '/produtos/camarao-red-turbo.jpg',
    category: 'Camarão Turbo',
  },

  // ── Pirata Turbo ───────────────────────────────────────────────────────────
  {
    id: 20,
    name: 'Pirata Turbo – Kill Bill',
    description: 'Kill Bill: amarelo e vermelho em contraste máximo. Isca agressiva para predadores territoriais.',
    price: 12.9,
    priceStr: 'R$ 12,90',
    size: '10 cm',
    image: '/produtos/pirata-turbo-kill-bill.jpg',
    category: 'Pirata Turbo',
  },
  {
    id: 21,
    name: 'Pirata Turbo – Musgo',
    description: 'Cor Musgo que mimetiza o fundo de rios e estuários. Altamente eficaz para peixes que caçam junto ao substrato.',
    price: 12.9,
    priceStr: 'R$ 12,90',
    size: '10 cm',
    image: '/produtos/pirata-turbo-musgo.jpg',
    category: 'Pirata Turbo',
  },

  // ── Shad Turbo ─────────────────────────────────────────────────────────────
  {
    id: 22,
    name: 'Shad Turbo – Kit Cores 1',
    description: 'Kit com 4 cores: Musgo, Amarelo, Fumaça (cauda vermelha) e Tricolor (cauda verde). Cobre todas as condições de pesca.',
    price: 14.9,
    priceStr: 'R$ 14,90',
    size: '10 cm — kit 4 cores',
    image: '/produtos/shad-turbo-musgo-amarelo-fumaca-cauda-vermelha-tricolor-cauda-verde.jpg',
    category: 'Shad Turbo',
  },
  {
    id: 23,
    name: 'Shad Turbo – Kit Cores 2',
    description: 'Kit com 5 cores: Salmon, Prateado, Amarelo (cauda laranja), Verde Fluorescente e Roxinho. Ideal para diversificar a caixa.',
    price: 14.9,
    priceStr: 'R$ 14,90',
    size: '10 cm — kit 5 cores',
    image: '/produtos/shad-turbo-salmon-prateado-amarelo-cauda-laranja-verde-florescente-roxinho.jpg',
    category: 'Shad Turbo',
  },

  // ── Shad Pirata ────────────────────────────────────────────────────────────
  {
    id: 24,
    name: 'Shad Pirata – Zico',
    description: 'O lendário Shad Zico, cor vermelha intensa com glitter dourado. Desenvolvido para pesca embarcada de alto mar.',
    price: 12.9,
    priceStr: 'R$ 12,90',
    size: '10 cm',
    image: '/produtos/shad-zico.jpg',
    category: 'Shad Pirata',
  },
  {
    id: 25,
    name: 'Shad Pirata – Roxo',
    description: 'Shad na cor Roxo — perfeito para pesca noturna e em águas com baixa luminosidade.',
    price: 12.9,
    priceStr: 'R$ 12,90',
    size: '10 cm',
    image: '/produtos/shad-pirata-roxo.jpg',
    category: 'Shad Pirata',
  },
  {
    id: 26,
    name: 'Shad Pirata – Coringa',
    description: 'O Coringa dos Shads — cor versátil que funciona em qualquer ambiente, horário e condição climática.',
    price: 12.9,
    priceStr: 'R$ 12,90',
    size: '10 cm',
    image: '/produtos/shads-coringa.jpg',
    category: 'Shad Pirata',
  },
  {
    id: 27,
    name: 'Shad Pirata – Pérola',
    description: 'Acabamento perolado com efeito iridescente. Destaque total em dias ensolarados com água cristalina.',
    price: 12.9,
    priceStr: 'R$ 12,90',
    size: '10 cm',
    image: '/produtos/shads-perola.jpg',
    category: 'Shad Pirata',
  },
  {
    id: 28,
    name: 'Shad Pirata – Glow',
    description: 'Glow: brilha no escuro! Indispensável para pesca noturna ou em fundos com pouca luz.',
    price: 12.9,
    priceStr: 'R$ 12,90',
    size: '10 cm',
    image: '/produtos/shads-pirata-glow.jpg',
    category: 'Shad Pirata',
  },
  {
    id: 29,
    name: 'Shad Pirata – Mexilhão',
    description: 'Cor Mexilhão que imita a cor natural do ambiente costeiro — robalo e linguado adoram.',
    price: 12.9,
    priceStr: 'R$ 12,90',
    size: '10 cm',
    image: '/produtos/shads-pirata-mexilhao.jpg',
    category: 'Shad Pirata',
  },
  {
    id: 30,
    name: 'Shad Pirata – Azul Cauda Glow',
    description: 'Corpo azul com cauda glow — combinação letal para pesca noturna em costeiras e píeres.',
    price: 12.9,
    priceStr: 'R$ 12,90',
    size: '10 cm',
    image: '/produtos/shads-pirata-azul-cauda-glow.jpg',
    category: 'Shad Pirata',
  },

  // ── Caixa / Kit ────────────────────────────────────────────────────────────
  {
    id: 31,
    name: 'Caixa Shad Pirata – Kit Sortido',
    description: 'Caixa organizadora com Shads Piratas sortidos — ideal para quem quer variedade de cores prontas para a próxima pescaria.',
    price: 89.9,
    priceStr: 'R$ 89,90',
    size: 'Kit sortido',
    image: '/produtos/caixa-shad-01.jpg',
    category: 'Caixa / Kit',
  },
]

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getFeaturedProducts(count = 3): Product[] {
  return products.slice(0, count)
}

export function getProductsByCategory(category: Product['category']): Product[] {
  return products.filter((p) => p.category === category)
}

export const categories: Product['category'][] = [
  'Camarão Turbo',
  'Pirata Turbo',
  'Shad Turbo',
  'Shad Pirata',
  'Caixa / Kit',
]
